### ISSUE TITLE
«Магические поля»

### ISSUE THREAD

**Issue by alexeyten** [yandex-ui/yandex-domain-configs#1]
Сейчас получается, что поля `domains`, `domainList` и `base` — «магические» и это нужно знать.

Может стоит их как-то явно обозначить, например `@extends` (или `$extends`) вместо `base`, `@domains` (или `$domains`) вместо `domains`.

**Comment by razetdinov** [comment]
Можно переименовать `base` в `extends` и предусмотреть опции `--domain-key`, `--domain-list-key`, `--extends-key`.

**Comment by alexeyten** [comment]
ИМХО, не нужно вводить параметры без необходимости.
